apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "rancher-project-mapper.fullname" . }}
  labels:
    app: {{ include "rancher-project-mapper.fullname" . }}
    chart: {{ include "rancher-project-mapper.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "rancher-project-mapper.gen-certs" . ) | indent 2 }}