apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-project-mapper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rancher-project-mapper.name" . }}
    helm.sh/chart: {{ include "rancher-project-mapper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rancher-project-mapper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rancher-project-mapper.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccount: {{ include "rancher-project-mapper.fullname" . }}
      serviceAccountName: {{ include "rancher-project-mapper.fullname" . }}
      volumes:
        - name: tls
          secret:
            defaultMode: 256
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            optional: false
            secretName: {{ include "rancher-project-mapper.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RPM_NAMESPACE
              value: "{{ .Values.configmap.namespace }}"
            - name: RPM_CONFIGMAP
              value: "{{ .Values.configmap.name }}"
            - name: RPM_LOGLEVEL
              value: "{{ .Values.loglevel }}"
            - name: TLS_CERT_FILE
              value: "{{ .Values.tls.files.crt }}"
            - name: TLS_KEY_FILE
              value: "{{ .Values.tls.files.key }}"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: "{{ .Values.tls.mountpath }}"
              name: tls
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
