apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rancher-project-mapper.fullname" . }}
  namespace: cattle-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]