apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-project-mapper
  namespace: cattle-system
data:
  config: |-
    {
      "rules": [
        {
          "regex": "rancher-project-mapper-*",
          "cluster": "c-12345",
          "project": "p-12345"
        }
      ]
    }