apiVersion: v1
kind: ConfigMap
metadata:
  name: rpm
  namespace: cattle-system
data:
  config: |-
    {
      "defaults": {
        "mapping": {
          "cluster": "c-4mdbz",
          "project": "p-n2d2p"
        },
        "creation": "allow"
      },
      "rules": {
        "mapping": [
        {
          "regex": "rpm-*",
          "cluster": "c-4mdbz",
          "project": "p-h75lh"
        }
        ],
        "creation": [
        {
          "regex": "mpr-*",
          "action": "deny"
        }
        ]
      }
    }