apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: "projectmapper.rancher.1eb100.net"
webhooks:
  - name: "projectmapper.rancher.1eb100.net"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["namespaces"]
        scope: "Cluster"
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxJQ0NRQ1lOYndYRktNTnJEQU5CZ2txaGtpRzl3MEJBUXNGQURCM01Rc3dDUVlEVlFRR0V3SlYKVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVNNQkFHQTFVRUJ3d0pRM1Z3WlhKMGFXNXZNUnN3R1FZRApWUVFLREJKU1lXNWphR1Z5SUV4aFluTXNJRWx1WXk0eElqQWdCZ05WQkFNTUdYSmhibU5vWlhJdGNISnZhbVZqCmRDMXRZWEJ3WlhJdFkyRXdIaGNOTVRreE1ERXdNREExTnpVMldoY05NakV4TURBNU1EQTFOelUyV2pCM01Rc3cKQ1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVNNQkFHQTFVRUJ3d0pRM1Z3WlhKMAphVzV2TVJzd0dRWURWUVFLREJKU1lXNWphR1Z5SUV4aFluTXNJRWx1WXk0eElqQWdCZ05WQkFNTUdYSmhibU5vClpYSXRjSEp2YW1WamRDMXRZWEJ3WlhJdFkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRGdDN1FwVmpJdzNMU2kvMTRuRkdZdFluOTk1TmFRZnRDSkpKd2kwa1ZzS09lbUNFd010dXlLKzdiRgpIcnU0QzkzdjRzRjIzcXJKRzlOQzhmM2tDOHJBSjJid0d6Um5OUmVBRDgxRjhidWVnZ3UzYXgyTVpVV3FnZzlPCkhCUEhuWlh0UEhwcWRnQWJWTXlwajhOSVVHWVFKRUdhWFd5M3J0Q0tKMk1TMTg0SjBPaXVzMFBJNjJUWDUzR3EKb1JkYWtkUy9hRjkvaXhrMlpqbThPR3l6RDMrMWtHSlYzb1p6SVpnUm56YUxpZ2FVWmlNSFAwTEExWG84RFJKcAo3TDRNTitGWHBzaldkQm4rMWlVSVNhZDBmeVMwWStFT2tjRUppUlcxNHhKa3BwMGdWMGkvME9lY3pkeEEwMXFPCm1EYUpreHNaVll3a2hHeGtobWVMbnExV2VMdHpBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEVloKcUlGdHhMQ09MRkxkbHdXcEN3RUIzUnQwSktVZW95UkpFQjZIVFlQY29ZTnRaaXBmM1p2VnhYZnlQRmJ6emNDWQphaklZZUJWeENKcEhHQURQbUF5MTNxSWdTdTlsT0ZEeUdma0Rjck02RGxsbXo1YWtPRFZYNHRVaENzZFRMaXVLCkJxNmJiNFgwYUhiUlJnQno5aFY4bUpSbk5VVU1adkgxek5CbVRmZ1lrSzYrczJzSFZDMXdNaXNldEhFYTdCRDYKSGViQlpnSGNYcEdxZWl0SGxZQUtUaVc2a1J5M0MxN3hxY1ErWjBGdWpBTDg0cmIzdEN5T3BsS2JLMlM4YXBkUQpmeVhrdWJQbzNWN0pYUThLeFVWbzNWSi85NGsxMis3azlucjhGU0VsVzFFSmp4b04yU0JTVTBITjVhN1luQnd3CnhXczcyaU1ZQzIzZXh6V2lqNWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      # service configuration
      #service:
      #  namespace: "cattle-system"
      #  name: "rancher-project-mapper"
      #  path: "/namespace"
      url: "https://192.168.1.100/namespace"
    sideEffects: None
    timeoutSeconds: 10